### ISSUE TITLE
Remove pyairports

### ISSUE THREAD

**Issue by lapp0** [dottxt-ai/outlines#1093]
### What behavior of the library made you think about the improvement?

We currently rely on a poorly maintained package, `pyairports`. The way this package is structured has caused a few build / test issues

- https://github.com/outlines-dev/outlines/issues/934
- https://github.com/outlines-dev/outlines/pull/1010#issuecomment-2270397514
- I've run into a few unreported headaches trying to test with pyairports as well.

The only use for pyairports in outlines is `outlines.types.airports`, in which we load `AIRPORT_IATA_LIST`. pyairports isn't maintained, so the list is presumably out of date.

### How would you like it to behave?

We should remove the `pyairports` dependency and use a different package.

```
import airportsdata
IATA_CODES = sorted(airportsdata.load().keys())
```

**Comment by cpfiffer** [comment]
Bump on this one. It's kind of an annoying issue, I often have to install `setuptools` and I believe it's the only package I need it for.
