### ISSUE TITLE
Numpy > 1.26.4

### ISSUE THREAD

**Issue by Mikeriess** [dottxt-ai/outlines#1104]
### What behavior of the library made you think about the improvement?

This issue is just meant as a Q&A, as I couldnt find anything specifically on this. 

The question is why there is a dependency on older versions of numpy? What is the limitation in the newer numpy versions? And how big of a job do you estimate it would be to support newer versions of numpy?

### How would you like it to behave?

Numpy > 1.26.4

**Comment by lapp0** [comment]
@Mikeriess I don't think it would be a substantial effort. 

We pinned to numpy 1 due to 

- https://github.com/outlines-dev/outlines/issues/976
- https://github.com/outlines-dev/outlines/pull/977

The imports would need to be fixed.

**Comment by Mikeriess** [comment]
Got it. Have had sime compatibility issues with the outlines and the newest llama.cpp version due to this, so if this is a trivial change that is great news 👍

**Comment by lapp0** [comment]
>Got it. Have had some compatibility issues with outlines and the newest llama.cpp version due to this, so if this is a trivial change that is great news 👍

Is the latest llama.cpp incompatible with `numpy<2.0.0`? If so, could you please share your error?

I'd like to ensure this is high priority if it breaks the latest llama.cpp.

**Comment by smallstepman** [comment]
https://github.com/abetlen/llama-cpp-python/blob/9769e5719ad45d4be6bc3ebe01d0f568d3d5001e/pyproject.toml#L16

https://github.com/vllm-project/vllm/blob/5231f0898e559671c6c8cc48efc53a859fce1841/requirements-common.txt#L3

looks like everyone is lagging behind

**Comment by jkohen** [comment]
Was the intention to allow importing numpy across all flavors of outlines? A few numpy<2 constraints remain in the optional packages, such as transformers: https://github.com/dottxt-ai/outlines/blob/main/pyproject.toml#L50-L54

On Windows pip wants to compile numpy 1.26.4 for some reason, and failing because I don't have a C++ dev environment. numpy 2.x got installed just fine.
