### ISSUE TITLE
The document is not exist

### ISSUE THREAD

**Issue by Haitons** [dottxt-ai/outlines#1147]
404 not found
![image](https://github.com/user-attachments/assets/17eaadc4-318d-4f9b-82a8-736e94f46755)

**Comment by cpfiffer** [comment]
Appreciate the report! This should be fixed by #1146

**Comment by cpfiffer** [comment]
This should work again, https://dottxt-ai.github.io/outlines/ is the new URL. Any links pointing to the old org URL at https://outlines-dev.github.io/outlines/ will return a 404. Closed by #1146
