### ISSUE TITLE
Importing `outlines` fails when `torch` is not installed, but `torch` is not a dependency

### ISSUE THREAD

**Issue by quernd** [dottxt-ai/outlines#1197]
### Describe the issue as clearly as possible:

Importing `outlines` fails when `torch` is not installed.

However, `torch` is not an explicit dependency. This is due to [a recent change](https://github.com/dottxt-ai/outlines/commit/faa7c5c77fbe7a0d2f1117d9fc8c407766614294#diff-23a937f0949980d655c7ca8c936d865c961e141f91d269b072731926e81dd7d5R4) that tries to import `torch` without [a guard like here](https://github.com/dottxt-ai/outlines/blob/d1b8728c6c65355f53a2c78432f8b07ad7518b7a/outlines/models/transformers.py#L163-L168).

### Steps/code to reproduce the bug:

```python
import outlines
```

### Expected result:

```shell
no error
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/code/outlines/outlines/__init__.py", line 2, in <module>
    import outlines.generate
  File "/home/daniel/code/outlines/outlines/generate/__init__.py", line 2, in <module>
    from .cfg import cfg
  File "/home/daniel/code/outlines/outlines/generate/cfg.py", line 7, in <module>
    from outlines.models import LlamaCpp, OpenAI, TransformersVision
  File "/home/daniel/code/outlines/outlines/models/__init__.py", line 11, in <module>
    from .exllamav2 import ExLlamaV2Model, exl2
  File "/home/daniel/code/outlines/outlines/models/exllamav2.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

### Outlines/Python version information:

Version is current `main` ([d1b8728](https://github.com/dottxt-ai/outlines/commit/d1b8728c6c65355f53a2c78432f8b07ad7518b7a))

Also present in `0.1.0`.

### Context for the issue:

Either `torch` shouldn't be a hard dependency; or else it should be, but then it should be listed in `pyproject.toml`.

**Comment by cpfiffer** [comment]
Related #1149
