### ISSUE TITLE
Move the logit processors to `outlines-core`

### ISSUE THREAD

**Issue by rlouf** [dottxt-ai/outlines#1206]
Related to https://github.com/dottxt-ai/outlines-core/issues/74

**Comment by Peng-YM** [comment]
It seems that this repo has been removed?

https://github.com/dottxt-ai/outlines-core

**Comment by rlouf** [comment]
It hasn't been opened (yet).

**Comment by rlouf** [comment]
After consideration, we will not be moving logit processors to `outlines-core`. The rationale is that we do not want to expose an interface whose implementation details depend on the internals of other libraries. Instead we will document best practices to avoid unnecessarily slow logit masking.
