### ISSUE TITLE
[Model Support] Pixtral model support

### ISSUE THREAD

**Issue by mlinmg** [dottxt-ai/outlines#1272]
### Describe the issue as clearly as possible:

When using Pixtral outlines gives an error, specifically in vllm.
The problems seems that mistral uses a different tokenizer (Tekken)

### Steps/code to reproduce the bug:

```python
from vllm import LLM

llm = LLM(
        model='mistralai/Pixtral-12B-2409,
        tokenizer_mode='mistral',
        max_model_len=3000,
        max_num_seqs=1,
        gpu_memory_utilization=0.9)
sampling_params = sampling_params = SamplingParams(
                        temperature=temp,
                        max_tokens=config.max_tokens,
                        guided_decoding=GuidedDecodingParams(
                            json=[insert a valid json schema]
                        )
                    )

# prepare the messages

llm.chat(messages, sampling_params)
```

### Expected result:

```shell
Some output following the schema
```

### Outlines/Python version information:

Version information
<details>
```
(command output here)
```
</details>

**Comment by rlouf** [comment]
@cpfiffer didn't you use Pixtral with Outlines?

**Comment by cpfiffer** [comment]
I did! @mlinmg can you look at this cookbook to see if that helps?

https://dottxt-ai.github.io/outlines/main/cookbook/receipt-digitization/

**Comment by mlinmg** [comment]
Yes sorry I found out about pixtral community later.
