### ISSUE TITLE
Is  there a way to use system prompt?

### ISSUE THREAD

**Issue by 2U1** [dottxt-ai/outlines#1328]
I couldn't find an example for using a system prompt with it. Is there a way to use system prompt?
I'm using MiniCPM-V_2_6 with transformer_vision.

**Comment by rlouf** [comment]
Not for now unfortunately, but we're currently refactoring prompting here: https://github.com/dottxt-ai/prompts

In the meantime we could push a quick feature here, it shouldn't be too hard to implement.

**Comment by rlouf** [comment]
Having said that, you could already use it by prompting the model. We should look at what the special tokens are for this model.

**Comment by 2U1** [comment]
Thanks for replying. 
Actually I'm using the config for 2_6 is 
https://huggingface.co/openbmb/MiniCPM-V-2_6/blob/main/tokenizer_config.json. 

Thanks for the kind reply.

**Comment by 2U1** [comment]
Also, I'm trying to use without the system prompt for now following the docs in the repo.
However it seems to be quite different from docs. 

I'm trying to load the model like
```
model = AutoModel.from_pretrained(model_id, trust_remote_code=True, torch_dtype=torch.bfloat16, attn_implementation='flash_attention_2') 
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

processor.image_processor.use_image_id = False

outlines_model = models.TransformersVision(model, tokenizer=tokenizer, processor=processor)
```

And then call the outlines_model something like this
```
image_data_generator = outlines_model.generate.json(model, Event)
```

However it shows `AttributeError: 'function' object has no attribute 'json'. Is the api for the library changed?

**Comment by 2U1** [comment]
I'm just using the model without the system prompt however I got some other problem.

I'm monkey pathcing the code for popping the `image_sizes` becuase the model dosen't use it when generating.
```
from outlines.models import TransformersVision

original_generate = TransformersVision.generate


def patched_generate(self, prompts, media, generation_parameters, logits_processor, sampling_parameters):
    inputs = self.processor(
        text=prompts, images=media, padding=True, return_tensors="pt"
    ).to(self.model.device)


    inputs.pop('image_sizes', None)


    generation_kwargs = self._get_generation_kwargs(
        prompts,
        generation_parameters,
        logits_processor,
        sampling_parameters,
    )
    generated_ids = self._generate_output_seq(prompts, inputs, **generation_kwargs)

    if isinstance(prompts, str):
        generated_ids = generated_ids.squeeze(0)

    return self._decode_generation(generated_ids)

TransformersVision.generate = patched_generate
```

Then initating the model as below.

```
model_id = "openbmb/MiniCPM-V-2_6"

model = AutoModel.from_pretrained(model_id, trust_remote_code=True, torch_dtype=torch.bfloat16, attn_implementation='flash_attention_2')
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

processor.image_processor.use_image_id = False

outlines_model = TransformersVision(model, tokenizer=tokenizer, processor=processor)
```

After this when I'm generating the result, the model generates nothing. I'm using the following code to generate
```
class Event(BaseModel):
    event: TrafficEvent
    weather: Weather
    reasoning_step: List[str] = Field(..., title="The reasoning steps leading to the final conclusion.")
    
image_data_generator = outlines.generate.json(outlines_model, Event)

user_text = "(<image>./</image>)\n" * len(groups) + system_prompt + '\n' + user_input

image_data_generator(
    user_text, groups
)
 ```
 
 Am I doing something wrong?

**Comment by 2U1** [comment]
I just solved this problem and also using system prompt with using LogitsProcessor.


Thanks for your great work!
