### ISSUE TITLE
Web server adapter

### ISSUE THREAD

**Issue by fshriver** [dottxt-ai/outlines#326]
Hi,

Is there going to be future support for abstracting the LLM behind a (non-OpenAI) API gateway? As in, if I have an LLM serving requests on some IP address, is there an adapter I could use besides the Huggingface and OpenAI ones to get outlines to work with that API? I don't have a sense for how big of an ask this is.

**Comment by fshriver** [comment]
To add a little more detail to this... in my case, I'd be interested in having a self-hosted GPU server running the actual LLM, with a separate process/server handling user state/queries to the LLM server/etc. `outlines` seems to only have support for Huggingface's `transformers` (which is manual and in the same process that Outlines is being run in) or `openai` (which is a complex API with a lot of knobs and switches). My question is, would it be possible to create an adapter for a generic web server so that you can use outlines in combination with any LLM resident on any server that you'd want? 

I've also given some thoughts that a portion of this ask could be accomplished by using the `openai` library with `api_base` set to the appropriate URL, however that would then rely on the LLM server supporting all the exact same functionality in the exact same way OpenAI does and I don't know how heavily outlines relies on OpenAI's built-in capabilities (tokenizer, function calling API, etc.) to function with that specific adapter.

**Comment by rlouf** [comment]
We are now considering adding this functionality in Outlines, assigning myself to the issue.
