### ISSUE TITLE
Integrate OpenAI functions with Pydantic

### ISSUE THREAD

**Issue by rlouf** [dottxt-ai/outlines#370]
### What behavior of the library made you think about the improvement?

OpenAI functions are not available via Outlines. However, we could use it for comparison purposes.

### How would you like it to behave?

We would like an API that is similar  to the current `text.generate.json` API or the same.

The main constraint with using the same function is that OpenAI’s response is not always parseable JSON. We could implement it in a separate `text.generate.openai.json` module.

**Comment by JerryKwan** [comment]
@rlouf 
We may need to change the implementation logic here 
https://github.com/outlines-dev/outlines/blob/main/outlines/generate/json.py#L71
right?

**Comment by rlouf** [comment]
These are the two entry points indeed.

**Comment by JerryKwan** [comment]
Thanks for the feedback, I will work on it ASAP
