### ISSUE TITLE
Add Anthropic integration

### ISSUE THREAD

**Issue by rlouf** [dottxt-ai/outlines#375]

**Comment by jakaline-dev** [comment]
Correct me if I'm wrong - for what I know, the anthropic/claude API does not have an API for outputting token probabilities yet

**Comment by rlouf** [comment]
That's correct, but we try to add other providers so people can compare their output to guided generation in outlines. I often need to do this.

**Comment by sztanko** [comment]
Anthropic is now available via AWS Bedrock: https://aws.amazon.com/bedrock/

I think it would be great to add support for Bedrock alltogether!

**Comment by shabie** [comment]
why was this idea of support for Bedrock dropped?

**Comment by rlouf** [comment]
The team has very limited resources

**Comment by shabie** [comment]
What if I volunteered to do this?

**Comment by jeremyallenjacobson** [comment]
With Bedrock, what is returned from the API request varies from one model to the next. 
For instance, the [Anthropic models response](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-text-completion.html) does not contain token probabilities in the response.
On the other hand, the [Cohere Command models response](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-cohere-command.html) will contain an array of per token likelihoods if you specify the return_likelihoods input parameter. I am not familiar enough with Outlines to know if that is enough.

**Comment by jeremyallenjacobson** [comment]
> Correct me if I'm wrong - for what I know, the anthropic/claude API does not have an API for outputting token probabilities yet

Yes, with Bedrock, what is returned from the API request varies from one model to the next.
For instance, the [Anthropic models response](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-text-completion.html) does not contain token probabilities in the response.
On the other hand, the [Cohere Command models response](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-cohere-command.html) will contain an array of per token likelihoods if you specify the return_likelihoods input parameter. I am not familiar enough with Outlines to know if that is enough.
