### ISSUE TITLE
Support for llama.cpp remote server

### ISSUE THREAD

**Issue by tranhoangnguyen03** [dottxt-ai/outlines#513]
I'm using Outline to write app logics on the client side. The llama.cpp server is deployed remotely. Is it possible to use Outline in this setup?

**Comment by mory91** [comment]
Outlines support openai client, llamacpp server supports openai server protocols. Set the openai server env variable to your llama cpp url, then use outlines openai's client.

**Comment by rlouf** [comment]
That's a very elegant solution!

**Comment by mjspeck** [comment]
+1 this functionality would be hugely beneficial since OpenAI doesn't support the JSON schema structure generation and I have a remote llama.cpp server.
