### ISSUE TITLE
 Amazon Bedrock Integration

### ISSUE THREAD

**Issue by dgallitelli** [dottxt-ai/outlines#767]
Before suggesting a new feature, please make sure this hasn't already been suggested by searching through the past issues and the PR tracker.

### Presentation of the new feature

Amazon Bedrock is an LLMs as a Service provided by Amazon Web Services. It support multiple Foundation Models, including Amazon Titan, Anthropic Claude 3, Llama 2, and embedding models. To have `outlines` support Amazon Bedrock, would mean that more than 10000 customers could use it for production. 

### Where does it fit in Outlines?

New integration, alongside Llama.cpp and OpenAI.

### Are you willing to open a PR?

Not a lot of time right now, so unfortunately not yet.

Thanks for contributing!

**Comment by jeremyallenjacobson** [comment]
See my post in a thread [here](https://github.com/outlines-dev/outlines/issues/375#issuecomment-2089148826) for why it may not be possible to support various models on Bedrock.
