### ISSUE TITLE
Use suffix automata for extractive generation

### ISSUE THREAD

**Issue by rlouf** [dottxt-ai/outlines#770]
### Discussed in https://github.com/outlines-dev/outlines/discussions/575

<div type='discussions-op-text'>

<sup>Originally posted by **JosephGatto** January 24, 2024</sup>
Is it possible to restrict the output to be any contiguous span of text from the input? 

In other words, I am wondering if Outlines can be used to do what would effectively be extractive inference? </div>

**Comment by xiaoyunwu** [comment]
https://paperswithcode.com/paper/automata-based-constraints-for-language-model
it is possible to support this?
